CREATE OR REPLACE FUNCTION "C##DB_COMET".get_quantita_mp_acquistata(
	p_CodiceMateriaPrima			IN MateriaPrima.CODICEMATERIAPRIMA%TYPE 
) RETURN NUMBER IS
	quantitaAcquistata NUMBER;
BEGIN
	SELECT SUM(da.QUANTITA)
	INTO quantitaAcquistata
	FROM ACQUISTO a
	JOIN DETTAGLIOACQUISTO da ON da.NUMEROFATTURA = a.NUMEROFATTURA 
	WHERE a.STATOORDINE = 'COMPLETATO' AND da.CODICEMATERIAPRIMA = p_CodiceMateriaPrima
	GROUP BY da.CODICEMATERIAPRIMA;
	
	RETURN quantitaAcquistata; 
END get_quantita_mp_acquistata;