CREATE OR REPLACE TRIGGER "C##DB_COMET".CHECK_USER_INSERT_UPDATE_ACQUISTO
AFTER INSERT OR UPDATE ON ACQUISTO
FOR EACH ROW
DECLARE
COUNT_DIPENDENTI NUMBER;
OPERATION_NOT_ALLOWED EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO COUNT_DIPENDENTI
    FROM DIPENDENTE
    WHERE CODICEFISCALE = :NEW.CODICEFISCALEDIPENDENTE
    AND MANSIONE != 'Acquisti';
    IF(COUNT_DIPENDENTI > 0) THEN
        RAISE OPERATION_NOT_ALLOWED;
    END IF;

    EXCEPTION
    WHEN OPERATION_NOT_ALLOWED
    THEN RAISE_APPLICATION_ERROR(-20020,'Utente non abilitato. Operazione non consentita.');
END;