TRIGGER DIPENDENTE_ASSENTE
BEFORE INSERT OR UPDATE ON TURNO
FOR EACH ROW 
DECLARE 
	DIPENDENTE_ASSENTE EXCEPTION;
	count_assenze NUMBER;
BEGIN 
	SELECT COUNT(*)
	INTO count_assenze
	FROM ASSENZA a 
	WHERE (a.DATAINIZIOASSENZA BETWEEN :NEW.DATAINIZIOTURNO AND :NEW.DATAFINETURNO) OR
	(a.DATAFINEASSENZA BETWEEN :NEW.DATAINIZIOTURNO AND :NEW.DATAFINETURNO);

	IF count_assenze > 0 THEN 
		RAISE DIPENDENTE_ASSENTE;
	END IF;

EXCEPTION
	WHEN DIPENDENTE_ASSENTE THEN
		RAISE_APPLICATION_ERROR(-20019, 'Nel periodo indicato l''utente è assente. Non è possibile procedere con l''inserimento/modifica.');
END;