CREATE OR REPLACE TRIGGER "C##DB_COMET".INSERIMENTOACQUISTOINCOERENTE
AFTER INSERT ON ACQUISTO

FOR EACH ROW
DECLARE
INSERT_NOT_VALID EXCEPTION;

BEGIN
    IF(:NEW.STATOORDINE = 'COMPLETATO' and :NEW.DATACONSEGNA is NULL) THEN
        RAISE INSERT_NOT_VALID;
    END IF;
    IF(:NEW.STATOORDINE != 'RICEVUTO' or :NEW.DATACONSEGNA is NOT NULL) THEN
        RAISE INSERT_NOT_VALID;
    END IF;

    EXCEPTION
    WHEN INSERT_NOT_VALID
    THEN RAISE_APPLICATION_ERROR(-20012,'Stato dell''ordine di acquisto incoerente. Non è possibile procedere con l''inserimento.');
END; 