CREATE OR REPLACE TRIGGER "C##DB_COMET".INSERIMENTO_MODIFICA_ACQUISTO_INCORENTE
AFTER INSERT OR UPDATE ON ACQUISTO

FOR EACH ROW
DECLARE
ACQUISTO_INCONSISTENT EXCEPTION;

BEGIN
    IF(:NEW.STATOORDINE = 'COMPLETATO' and :NEW.DATACONSEGNA is NULL) THEN
        RAISE ACQUISTO_INCONSISTENT;
    END IF;

    IF(:NEW.STATOORDINE != 'COMPLETATO' and :NEW.DATACONSEGNA is NULL) THEN
        RAISE ACQUISTO_INCONSISTENT;
    END IF;

    EXCEPTION
    WHEN ACQUISTO_INCONSISTENT
    THEN RAISE_APPLICATION_ERROR(-20012,'Stato dell''ordine di acquisto incoerente. Non è possibile procedere con l''operazione.');
END;