CREATE OR REPLACE TRIGGER TURNI_SOVRAPPOSTI
BEFORE INSERT OR UPDATE ON TURNO
FOR EACH ROW
DECLARE
	TURNI_SOVRAPPOSTI EXCEPTION;
	count_turni NUMBER;
BEGIN
	SELECT COUNT(*)
	INTO count_turni 
	FROM TURNO t 
	WHERE 
	(
		(:NEW.DATAINIZIOTURNO BETWEEN t.DATAINIZIOTURNO AND t.DATAFINETURNO) OR 
		(:NEW.DATAFINETURNO BETWEEN t.DATAINIZIOTURNO AND t.DATAFINETURNO)
	) AND t.CFDIPENDENTE = :NEW.CFDIPENDENTE;

	IF count_turni > 0 THEN
		RAISE TURNI_SOVRAPPOSTI;
	END IF;
EXCEPTION
	WHEN TURNI_SOVRAPPOSTI THEN 
		RAISE_APPLICATION_ERROR(-20015,'L''utente ha già un turno programmato per l''intervallo di tempo indicato. Non è possibile procedere con l''inserimento/aggiornamento.');
END;