/*  */
CREATE OR REPLACE TRIGGER "C##DB_COMET".CHECK_USER_INSERT_UPDATE_ACQUISTO
AFTER INSERT OR UPDATE ON ACQUISTO
FOR EACH ROW
DECLARE
COUNT_DIPENDENTI NUMBER;
OPERATION_NOT_ALLOWED EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO COUNT_DIPENDENTI
    FROM DIPENDENTE
    WHERE CODICEFISCALE = :NEW.CODICEFISCALEDIPENDENTE
    AND MANSIONE != 'Acquisti';
    IF(COUNT_DIPENDENTI > 0) THEN
        RAISE OPERATION_NOT_ALLOWED;
    END IF;

    EXCEPTION
    WHEN OPERATION_NOT_ALLOWED
    THEN RAISE_APPLICATION_ERROR(-20020,'Utente non abilitato. Operazione non consentita.');
END;

/*  Verifica se la data consegna inserita per l'acquisto è minore della data ordine */
CREATE OR REPLACE TRIGGER "C##DB_COMET".DATE_ACQUISTO_INCORENTI
BEFORE INSERT OR UPDATE ON ACQUISTO
FOR EACH ROW
DECLARE
DATE_NON_VALIDE EXCEPTION;
BEGIN
	IF(:NEW.DATACONSEGNA - :NEW.DATAORDINE) < 0 THEN
		RAISE DATE_NON_VALIDE;
	END IF;
EXCEPTION
	WHEN DATE_NON_VALIDE THEN 
		RAISE_APPLICATION_ERROR(-20009,'DATACONSEGNA antecedente a DATAACQUISTO. Non è possibile procedere con l''aggiornamento/la modifica.');
END;

/*  Verifica se la data consegna inserita per la vendita è minore della data ordine */
CREATE OR REPLACE TRIGGER "C##DB_COMET".DATE_VENDITA_INCORENTI
BEFORE INSERT OR UPDATE ON VENDITA
FOR EACH ROW
DECLARE
DATE_NON_VALIDE EXCEPTION;
BEGIN
	IF(:NEW.DATACONSEGNA - :NEW.DATAORDINE) < 0 THEN
		RAISE DATE_NON_VALIDE;
	END IF;
EXCEPTION
	WHEN DATE_NON_VALIDE THEN 
		RAISE_APPLICATION_ERROR(-20010,'DATACONSEGNA antecedente a DATAACQUISTO. Non è possibile procedere con l''aggiornamento/la modifica.');
END;

/* Verifica se l'utente associato al turno è assente nello stesso periodo e in caso positivo blocca l'inserimento/aggiornamento */
TRIGGER "C##DB_COMET".DIPENDENTE_ASSENTE
BEFORE INSERT OR UPDATE ON TURNO
FOR EACH ROW 
DECLARE 
	DIPENDENTE_ASSENTE EXCEPTION;
	count_assenze NUMBER;
BEGIN 
	SELECT COUNT(*)
	INTO count_assenze
	FROM ASSENZA a 
	WHERE a.CODICEFISCALEDIPENDENTE = :NEW.CFDIPENDENTE AND
	(	
		(a.DATAINIZIOASSENZA BETWEEN :NEW.DATAINIZIOTURNO AND :NEW.DATAFINETURNO) OR
		(a.DATAFINEASSENZA BETWEEN :NEW.DATAINIZIOTURNO AND :NEW.DATAFINETURNO)
	);

	IF count_assenze > 0 THEN 
		RAISE DIPENDENTE_ASSENTE;
	END IF;

EXCEPTION
	WHEN DIPENDENTE_ASSENTE THEN
		RAISE_APPLICATION_ERROR(-20019, 'Nel periodo indicato l''utente è assente. Non è possibile procedere con l''inserimento/modifica.');
END;


/* Verifica se la durata del turno è di 8 ore. In caso negativo non permette di procedere con l'inserimento/aggiornamento */
CREATE OR REPLACE TRIGGER "C##DB_COMET".DURATA_TURNO_NON_VALIDA
BEFORE INSERT OR UPDATE ON TURNO
FOR EACH ROW 
DECLARE
	DURATA_NON_VALIDA EXCEPTION;
BEGIN 
	IF (:NEW.DATAFINETURNO - :NEW.DATAINIZIOTURNO) * 24 != 8 THEN 
		RAISE DURATA_NON_VALIDA;
	END IF;

EXCEPTION
	WHEN DURATA_NON_VALIDA THEN
		RAISE_APPLICATION_ERROR(-20018, 'Durata del turno non valida. Non è possibile procedere con l''inserimento/aggiornamento.');
END;

/* Inibisce la modifica di una formula se questa è calendarizzata nel futuro. */
CREATE OR REPLACE TRIGGER "C##DB_COMET".formula_calendarizzata
BEFORE UPDATE ON FORMULA
FOR EACH ROW 
DECLARE 
	FORMULA_CALENDARIZZATA EXCEPTION;
BEGIN
	IF is_formula_calendarizzata(:OLD.CODICEFORMULA) THEN
		RAISE FORMULA_CALENDARIZZATA;
	END IF;

EXCEPTION
	WHEN FORMULA_CALENDARIZZATA THEN
		RAISE_APPLICATION_ERROR(-20015, 'La formula è calendarizzata nel futuro. Non è possibile procedere con l''aggiornamento.');
END;


/* Inibisce la modifica della relazione tra materia prima e la formula nel caso in cui la formula sia calendarizzata nel futuro */
CREATE OR REPLACE TRIGGER "C##DB_COMET".formula_materia_prima_calendarizzata
BEFORE UPDATE ON FORMULA_MATERIAPRIMA
FOR EACH ROW 
DECLARE 
	FORMULA_CALENDARIZZATA EXCEPTION;
BEGIN
	IF is_formula_calendarizzata(:OLD.CODICEFORMULA) THEN
		RAISE FORMULA_CALENDARIZZATA;
	END IF;

EXCEPTION
	WHEN FORMULA_CALENDARIZZATA THEN
		RAISE_APPLICATION_ERROR(-20015, 'La formula è calendarizzata nel futuro. Non è possibile procedere con l''aggiornamento.');
END;


/* Verifica se lo stato ordine e la data consegna dell'acquisto sono correttamente impostati.  */
CREATE OR REPLACE TRIGGER "C##DB_COMET".INSERIMENTO_MODIFICA_ACQUISTO_INCORENTE
AFTER INSERT OR UPDATE ON ACQUISTO

FOR EACH ROW
DECLARE
ACQUISTO_INCONSISTENT EXCEPTION;

BEGIN
    IF(:NEW.STATOORDINE = 'COMPLETATO' and :NEW.DATACONSEGNA is NULL) THEN
        RAISE ACQUISTO_INCONSISTENT;
    END IF;

    IF(:NEW.STATOORDINE != 'COMPLETATO' and :NEW.DATACONSEGNA is NULL) THEN
        RAISE ACQUISTO_INCONSISTENT;
    END IF;

    EXCEPTION
    WHEN ACQUISTO_INCONSISTENT
    THEN RAISE_APPLICATION_ERROR(-20012,'Stato dell''ordine di acquisto incoerente. Non è possibile procedere con l''operazione.');
END;

/* Verifica se lo stato ordine e la data consegna della vendita sono correttamente impostati.  */
CREATE OR REPLACE TRIGGER "C##DB_COMET".STATO_INSERIMENTO_MODIFICA_VENDITA_INCOERENTE
BEFORE INSERT OR UPDATE ON VENDITA
FOR EACH ROW
DECLARE
STATO_VENDITA_INCOERENTE EXCEPTION;
BEGIN
	IF :NEW.STATOORDINE = 'COMPLETATO' AND :NEW.DATACONSEGNA IS NULL THEN
		RAISE STATO_VENDITA_INCOERENTE;
	END IF;

	IF :NEW.STATOORDINE != 'COMPLETATO' AND :NEW.DATACONSEGNA IS NOT NULL THEN
		RAISE STATO_VENDITA_INCOERENTE;
	END IF;
EXCEPTION
	WHEN STATO_VENDITA_INCOERENTE THEN 
		RAISE_APPLICATION_ERROR(-20013,'Stato Vendita incoerente. Non è possibile procedere con l''inserimento.');
END;
