	CREATE OR REPLACE VIEW "C##DB_COMET"."INVENTARIO_MATERIE_PRIME" ("CODICEMATERIAPRIMA", "NOMEPRODOTTO", "QUANTITADAUTILIZZARE", "QUANTITAACQUISTATA", "QUANTITADAACQUISTARE") AS 
	SELECT 
		m.CODICEMATERIAPRIMA, 
		m.NOMEPRODOTTO, 
		NVL(MAX(mp_necessarie.QUANTITADAUTILIZZARE), 0) AS QUANTITADAUTILIZZARE, 
		NVL(SUM(da.QUANTITA), 0) AS QUANTITAACQUISTATA,
		NVL(MAX(mp_necessarie.QUANTITADAUTILIZZARE), 0) - NVL(SUM(da.QUANTITA), 0) AS QUANTITADAACQUISTARE
	FROM "C##DB_COMET".MATERIAPRIMA m 
	LEFT JOIN (
		SELECT 
			fm.CODICEMATERIAPRIMA, 
			SUM(fm.QUANTITADAUTILIZZARE) AS QUANTITADAUTILIZZARE
		FROM "C##DB_COMET".CALENDARIOPRODUZIONE c 
		JOIN "C##DB_COMET".PRODOTTOFINITO p ON p.CODICEPRODOTTOFINITO = c.CODICEPRODOTTOFINITO 
		JOIN "C##DB_COMET".FORMULA f ON f.CODICEPRODOTTOFINITO = p.CODICEPRODOTTOFINITO 
		JOIN "C##DB_COMET".FORMULA_MATERIAPRIMA fm ON fm.CODICEFORMULA = f.CODICEFORMULA 
		GROUP BY fm.CODICEMATERIAPRIMA
	) mp_necessarie ON mp_necessarie.CODICEMATERIAPRIMA = m.CODICEMATERIAPRIMA
	LEFT JOIN "C##DB_COMET".DETTAGLIOACQUISTO da ON da.CODICEMATERIAPRIMA = m.CODICEMATERIAPRIMA
	GROUP BY m.CODICEMATERIAPRIMA, m.NOMEPRODOTTO
	ORDER BY m.CODICEMATERIAPRIMA;

	CREATE OR REPLACE VIEW "C##DB_COMET"."ACQUISTO_MP" ("PIVAAZIENDA", "CODICEMATERIAPRIMA", "QUANTITA_DA_ACQUISTARE", "COSTO_TOTALE") AS 
	SELECT
		mp_aconv.PIVAAZIENDA,
		mp_aconv.CODICEMATERIAPRIMA,
		mp_aconv.QUANTITA_DA_ACQUISTARE,
		mp_aconv.COSTO_TOTALE
	FROM (
	SELECT 
		amp.PIVAAZIENDA, 
		mp.CODICEMATERIAPRIMA,
		CASE 
			WHEN imp.QUANTITADAACQUISTARE >= amp.QUANTITAMINIMADAACQUISTARE THEN
				CEIL((imp.QUANTITADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.QUANTITAPRODOTTO 
			ELSE 
				CEIL((amp.QUANTITAMINIMADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.QUANTITAPRODOTTO
		END AS QUANTITA_DA_ACQUISTARE,
		CASE 
			WHEN imp.QUANTITADAACQUISTARE >= amp.QUANTITAMINIMADAACQUISTARE THEN
				CEIL((imp.QUANTITADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.PREZZOPRODOTTO
			ELSE 
				CEIL((amp.QUANTITAMINIMADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.PREZZOPRODOTTO
		END AS COSTO_TOTALE
	FROM "C##DB_COMET".AZIENDA_MATERIAPRIMA amp
	JOIN "C##DB_COMET".MATERIAPRIMA mp ON mp.CODICEMATERIAPRIMA = amp.CODICEMATERIAPRIMA 
	JOIN "C##DB_COMET".INVENTARIO_MATERIE_PRIME imp ON imp.CODICEMATERIAPRIMA = mp.CODICEMATERIAPRIMA 
	WHERE imp.QUANTITADAACQUISTARE > 0
	) mp_aconv
	WHERE mp_aconv.COSTO_TOTALE = (
		SELECT 
			MIN(mp_aconv1.COSTO_TOTALE) AS COSTO_TOTALE
		FROM (
		SELECT 
			mp.CODICEMATERIAPRIMA,
			CASE 
				WHEN imp.QUANTITADAACQUISTARE >= amp.QUANTITAMINIMADAACQUISTARE THEN
					CEIL((imp.QUANTITADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.PREZZOPRODOTTO
				ELSE 
					CEIL((amp.QUANTITAMINIMADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.PREZZOPRODOTTO
			END AS COSTO_TOTALE
		FROM "C##DB_COMET".AZIENDA_MATERIAPRIMA amp
		JOIN "C##DB_COMET".MATERIAPRIMA mp ON mp.CODICEMATERIAPRIMA = amp.CODICEMATERIAPRIMA 
		JOIN "C##DB_COMET".INVENTARIO_MATERIE_PRIME imp ON imp.CODICEMATERIAPRIMA = mp.CODICEMATERIAPRIMA 
		WHERE imp.QUANTITADAACQUISTARE > 0
		ORDER BY imp.CODICEMATERIAPRIMA 
		) mp_aconv1
		WHERE mp_aconv1.CODICEMATERIAPRIMA = mp_aconv.CODICEMATERIAPRIMA
		GROUP BY mp_aconv.CODICEMATERIAPRIMA
	)
	ORDER BY mp_aconv.CODICEMATERIAPRIMA;

	CREATE OR REPLACE VIEW "C##DB_COMET"."INVENTARIO_PRODOTTI_FINITI" ("CODICEPRODOTTOFINITO", "NOMEPRODOTTO", "QUANTITAPRODOTTA", "QUANTITACALENDARIZZATA", "QUANTITAVENDUTA", "QUANTITARIMANENTE") AS 
	SELECT
		p.CODICEPRODOTTOFINITO, 
		p.NOMEPRODOTTO, 
		NVL(MAX(pf_prodotti.QUANTITAPRODOTTA), 0) AS QUANTITAPRODOTTA,
		NVL(MAX(pf_da_produrre.QUANTITAPRODOTTA), 0) AS QUANTITACALENDARIZZATA,
		NVL(SUM(dv.QUANTITA), 0) AS QUANTITAVENDUTA,
		NVL(MAX(pf_prodotti.QUANTITAPRODOTTA), 0) + NVL(MAX(pf_da_produrre.QUANTITAPRODOTTA), 0) - NVL(SUM(dv.QUANTITA), 0) AS QUANTITARIMANENTE
	FROM "C##DB_COMET".PRODOTTOFINITO p 
	LEFT JOIN (
		SELECT 
			pf.CODICEPRODOTTOFINITO, 
			SUM(f.PRODUZIONEPREVISTA) AS QUANTITAPRODOTTA
		FROM "C##DB_COMET".CALENDARIOPRODUZIONE c
		JOIN "C##DB_COMET".PRODOTTOFINITO pf ON pf.CODICEPRODOTTOFINITO = c.CODICEPRODOTTOFINITO
		JOIN "C##DB_COMET".FORMULA f ON f.CODICEPRODOTTOFINITO = pf.CODICEPRODOTTOFINITO
		WHERE c.DATAFINEPRODUZIONE < SYSDATE
		GROUP BY pf.CODICEPRODOTTOFINITO 
	) pf_prodotti ON pf_prodotti.CODICEPRODOTTOFINITO= p.CODICEPRODOTTOFINITO 
	LEFT JOIN (
		SELECT 
			pf.CODICEPRODOTTOFINITO, 
			SUM(f.PRODUZIONEPREVISTA) AS QUANTITAPRODOTTA
		FROM "C##DB_COMET".CALENDARIOPRODUZIONE c
		JOIN "C##DB_COMET".PRODOTTOFINITO pf ON pf.CODICEPRODOTTOFINITO = c.CODICEPRODOTTOFINITO
		JOIN "C##DB_COMET".FORMULA f ON f.CODICEPRODOTTOFINITO = pf.CODICEPRODOTTOFINITO
		WHERE c.DATAFINEPRODUZIONE >= SYSDATE
		GROUP BY pf.CODICEPRODOTTOFINITO 
	) pf_da_produrre ON pf_da_produrre.CODICEPRODOTTOFINITO= p.CODICEPRODOTTOFINITO
	LEFT JOIN "C##DB_COMET".DETTAGLIOVENDITA dv ON dv.CODICEPRODOTTOFINITO = p.CODICEPRODOTTOFINITO
	LEFT JOIN "C##DB_COMET".VENDITA v ON v.NUMEROFATTURA = dv.NUMEROFATTURA 
	WHERE v.STATOORDINE != 'ANNULLATO'
	GROUP BY p.CODICEPRODOTTOFINITO, p.NOMEPRODOTTO
	ORDER BY p.CODICEPRODOTTOFINITO;