create table "C##DB_COMET".MateriaPrima (
	CodiceMateriaPrima VARCHAR2(10) PRIMARY KEY,
	NomeProdotto VARCHAR2(50) NOT NULL UNIQUE,
	UnitaMisura VARCHAR2(2) NOT NULL,
	Vegano VARCHAR2(1) NOT NULL,
	
	CONSTRAINT CHECK_VEGANO_MP CHECK(Vegano IN ('Y','N')),
	CONSTRAINT CHECK_UNITA_MISURA_MP CHECK(UnitaMisura IN ('Kg','L'))
);

INSERT INTO MateriaPrima (CodiceMateriaPrima, NomeProdotto, UnitaMisura, Vegano) VALUES
('MP-1', 'Water', 'L', 'Y'),
('MP-2', 'Sodium Lauroyl Methyl Isethionate', 'Kg', 'Y'),
('MP-3', 'Cocamidopropyl Betaine', 'L', 'N'),
('MP-4', 'Decyl Glucoside', 'Kg', 'Y'),
('MP-5', 'Fragrance', 'Kg', 'N'),
('MP-6', 'Sodium Cocoyl Alaninate', 'Kg', 'Y'),
('MP-7', 'Polysorbate 20', 'L', 'Y'),
('MP-8', 'Sodium Methyl Isethionate', 'Kg', 'Y'),
('MP-9', 'Betaine', 'Kg', 'N'),
('MP-10', 'Lauric Acid', 'Kg', 'Y'),
('MP-11', 'C10-30 Alkyl Acrylate Crosspolymer', 'Kg', 'Y'),
('MP-12', 'Benzyl Alcohol', 'L', 'Y'),
('MP-13', 'Brassicamidopropyl Dimethylamine', 'L', 'Y'),
('MP-14', 'Coco-Glucoside', 'Kg', 'Y'),
('MP-15', 'Sodium Chloride', 'Kg', 'Y'),
('MP-16', 'Glyceryl Oleate', 'Kg', 'N'),
('MP-17', 'Sodium Benzoate', 'Kg', 'Y'),
('MP-18', 'Glycol Distearate', 'Kg', 'Y'),
('MP-19', 'Trisodium Ethylenediamine Disuccinate', 'Kg', 'Y'),
('MP-20', 'Polyquaternium-7', 'L', 'N'),
('MP-21', 'Phenethyl Benzoate', 'Kg', 'Y'),
('MP-22', 'Sodium Laurate', 'Kg', 'Y'),
('MP-23', 'Polyquaternium-10', 'Kg', 'N'),
('MP-24', 'Coconut Acid', 'Kg', 'Y'),
('MP-25', 'Tetrasodium Glutamate Diacetate', 'Kg', 'Y'),
('MP-26', 'Guar Hydroxypropyltrimonium Chloride', 'Kg', 'Y'),
('MP-27', 'Citric Acid', 'Kg', 'Y'),
('MP-28', 'Genipa Americana Fruit Extract', 'Kg', 'Y'),
('MP-29', 'Alpha-Isomethyl Ionone', 'Kg', 'N'),
('MP-30', 'Linalool', 'Kg', 'N'),
('MP-31', 'Corn Starch Modified', 'Kg', 'Y'),
('MP-32', 'Glyceryl Stearate', 'Kg', 'N'),
('MP-33', 'Tocopherol', 'Kg', 'Y'),
('MP-34', 'Sodium Hydroxide', 'Kg', 'Y'),
('MP-35', 'Coumarin', 'Kg', 'N'),
('MP-36', 'Hydrolyzed Adansonia Digitata Seed Extract', 'Kg', 'Y'),
('MP-37', 'Glycine Soja Oil', 'L', 'N'),
('MP-39', 'SODIUM LAURETH SULFATE', 'Kg', 'N'),
('MP-41', 'DISTEARETH-75 IPDI', 'Kg', 'N'),
('MP-42', 'PPG-3 BENZYL ETHER MYRISTATE', 'L', 'N'),
('MP-43', 'GLYCERETH-7 CAPRYLATE/CAPRATE', 'L', 'N'),
('MP-44', 'COCAMIDOPROPYL BETAINE', 'L', 'N'),
('MP-45', 'COCAMIDE MEA', 'L', 'N'),
('MP-46', 'DECYL GLUCOSIDE', 'L', 'Y'),
('MP-47', 'GLYCINE', 'Kg', 'Y'),
('MP-48', 'ALANINE', 'Kg', 'Y'),
('MP-49', 'SERINE', 'Kg', 'Y'),
('MP-50', 'VALINE', 'Kg', 'Y'),
('MP-51', 'SODIUM PCA', 'Kg', 'Y'),
('MP-52', 'SODIUM LACTATE', 'L', 'Y'),
('MP-53', 'CARAMEL', 'L', 'Y'),
('MP-54', 'PHYTANTRIOL', 'Kg', 'N'),
('MP-55', 'ARGININE', 'Kg', 'Y'),
('MP-56', 'PANTHENOL', 'Kg', 'N'),
('MP-57', 'ASPARTIC ACID', 'Kg', 'Y'),
('MP-58', 'PCA', 'Kg', 'Y'),
('MP-59', 'PROLINE', 'Kg', 'Y'),
('MP-60', 'THREONINE', 'Kg', 'Y'),
('MP-61', 'ISOLEUCINE', 'Kg', 'Y'),
('MP-62', 'HISTIDINE', 'Kg', 'Y'),
('MP-63', 'PHENYLALANINE', 'Kg', 'Y'),
('MP-64', 'BUTYROSPERMUM PARKII (SHEA) BUTTER', 'Kg', 'Y'),
('MP-65', 'ARCTIUM LAPPA ROOT EXTRACT', 'L', 'Y'),
('MP-66', 'ROSMARINUS OFFICINALIS (ROSEMARY) LEAF EXTRACT', 'L', 'Y'),
('MP-67', 'URTICA DIOICA (NETTLE) LEAF EXTRACT', 'L', 'Y'),
('MP-68', 'SALVIA OFFICINALIS (SAGE) LEAF EXTRACT', 'L', 'Y'),
('MP-69', 'CHAMOMILLA RECUTITA (MATRICARIA) FLOWER EXTRACT', 'L', 'Y'),
('MP-70', 'PEG-150 DISTEARATE', 'Kg', 'N'),
('MP-71', 'CAPRYLYL GLYCOL', 'L', 'Y'),
('MP-72', 'GUAR HYDROXYPROPYLTRIMONIUM CHLORIDE', 'Kg', 'Y'),
('MP-73', 'GLYCERIN', 'L', 'Y'),
('MP-74', 'CHLORPHENESIN', 'Kg', 'N'),
('MP-75', 'SODIUM BENZOATE', 'Kg', 'Y'),
('MP-76', 'CAPRYLHYDROXAMIC ACID', 'Kg', 'N'),
('MP-77', 'POLYSORBATE 20', 'L', 'Y'),
('MP-78', 'STYRAX BENZOIN GUM', 'Kg', 'N'),
('MP-79', 'VITIS VINIFERA (GRAPE) SEED OIL', 'L', 'Y'),
('MP-80', 'PHENOXYETHANOL', 'L', 'N'),
('MP-83', 'BENZYL BENZOATE', 'L', 'N'),
('MP-84', 'BENZYL SALICYLATE', 'L', 'N'),
('MP-85', 'CITRONELLOL', 'Kg', 'Y'),
('MP-86', 'COUMARIN', 'Kg', 'Y'),
('MP-87', 'HEXYL CINNAMAL', 'Kg', 'Y'),
('MP-88', 'HYDROXYCITRONELLAL', 'Kg', 'N'),
('MP-90', 'YELLOW 5 (CI 19140)', 'Kg', 'N'),
('MP-92', 'Cetearyl Alcohol', 'Kg', 'Y'),
('MP-93', 'Glycerin', 'Kg', 'Y'),
('MP-94', 'Behentrimonium Chloride', 'Kg', 'Y'),
('MP-95', 'Cetearyl Ethylhexanoate', 'Kg', 'Y'),
('MP-96', 'Pentylene Glycol', 'Kg', 'Y'),
('MP-97', 'Cetyl Esters', 'Kg', 'Y'),
('MP-98', 'Biotin', 'Kg', 'Y'),
('MP-99', 'Butyrospermum Parkii (Shea) Butter', 'Kg', 'Y'),
('MP-100', 'Calcium DNA', 'Kg', 'Y'),
('MP-101', 'Hydrolyzed Keratin', 'Kg', 'Y'),
('MP-102', 'Keratin', 'Kg', 'Y'),
('MP-103', 'Lecithin', 'Kg', 'Y'),
('MP-104', 'Magnesium DNA', 'Kg', 'Y'),
('MP-105', 'Palmitoyl Myristyl Serinate', 'Kg', 'Y'),
('MP-106', 'Panthenol', 'Kg', 'Y'),
('MP-107', 'Pantolactone', 'Kg', 'Y'),
('MP-108', 'RNA', 'Kg', 'Y'),
('MP-109', 'Rosa Moschata Seed Oil', 'L', 'Y'),
('MP-110', 'Silanetriol Lysinate', 'Kg', 'Y'),
('MP-111', 'Sodium DNA', 'Kg', 'Y'),
('MP-112', 'Urea', 'Kg', 'Y'),
('MP-113', 'Ceteareth-20', 'Kg', 'Y'),
('MP-115', 'Disodium EDTA', 'Kg', 'Y'),
('MP-116', 'Isopropyl Alcohol', 'L', 'Y'),
('MP-117', 'PEG-8', 'Kg', 'Y'),
('MP-118', 'SMDI Copolymer', 'Kg', 'Y'),
('MP-120', 'Propylene Glycol', 'L', 'Y'),
('MP-121', 'Sodium Acetate', 'Kg', 'Y'),
('MP-123', 'Sodium Polyacrylate', 'Kg', 'Y'),
('MP-124', 'Caramel', 'Kg', 'Y'),
('MP-125', 'Yellow 5 (CI 19140)', 'Kg', 'Y'),
('MP-126', 'Chlorphenesin', 'Kg', 'Y'),
('MP-130', 'Benzyl Salicylate', 'Kg', 'Y'),
('MP-132', 'Hexyl Cinnamal', 'Kg', 'Y'),
('MP-133', 'Limonene', 'Kg', 'Y'),
('MP-137', 'Propanediol', 'Kg', 'Y'),
('MP-138', 'Behentrimonium Methosulfate', 'Kg', 'Y'),
('MP-139', 'Cocos Nucifera (Coconut) Oil', 'Kg', 'Y'),
('MP-140', 'Emblica Officinalis (Amla) Fruit Extract', 'Kg', 'Y'),
('MP-141', 'Curcuma Longa (Turmeric) Root Extract', 'Kg', 'Y'),
('MP-142', 'Panax Ginseng (Ginseng) Root Extract', 'Kg', 'Y'),
('MP-143', 'Centella Asiatica (Hydrocotyl) Extract', 'Kg', 'Y'),
('MP-144', 'Aleurites Moluccana (Kukui) Seed Oil', 'Kg', 'Y'),
('MP-145', 'Caffeine', 'Kg', 'Y'),
('MP-146', 'Tocopherol (Vitamin E)', 'Kg', 'Y'),
('MP-147', 'Hydrolyzed Soy Protein', 'Kg', 'Y'),
('MP-148', 'Malt Extract', 'Kg', 'Y'),
('MP-149', 'Adenosine Phosphate', 'Kg', 'Y'),
('MP-150', 'Creatine', 'Kg', 'Y'),
('MP-151', 'Yeast Extract', 'Kg', 'Y'),
('MP-152', 'Acetyl Carnitine Hcl', 'Kg', 'Y'),
('MP-153', 'Dihydroxypropyl Arginine Hcl', 'Kg', 'Y'),
('MP-154', 'Distearyldimonium Chloride', 'Kg', 'Y'),
('MP-155', 'Caprylyl Glycol', 'Kg', 'Y'),
('MP-156', 'Dimethicone', 'Kg', 'Y'),
('MP-157', 'Methyl Trimethicone', 'Kg', 'Y'),
('MP-158', 'Dimethicone Peg-8 Polyacrylate', 'Kg', 'Y'),
('MP-159', 'Polyglyceryl-10 Laurate', 'Kg', 'Y'),
('MP-160', 'Dimethicone Copolymer', 'Kg', 'Y'),
('MP-163', 'Eugenol', 'Kg', 'Y'),
('MP-164', 'Geraniol', 'Kg', 'Y'),
('MP-166', 'Citral', 'Kg', 'Y'),
('MP-167', 'Benzyl Benzoate', 'Kg', 'Y'),
('MP-169', 'Potassium Sorbate', 'Kg', 'Y');
