-- "C##DB_COMET".ACQUISTO_MP source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##DB_COMET"."ACQUISTO_MP" ("PIVAAZIENDA", "CODICEMATERIAPRIMA", "QUANTITA_DA_ACQUISTARE", "COSTO_TOTALE") AS 
  SELECT
	mp_aconv.PIVAAZIENDA,
	mp_aconv.CODICEMATERIAPRIMA,
	mp_aconv.QUANTITA_DA_ACQUISTARE,
	mp_aconv.COSTO_TOTALE
FROM (
SELECT 
	amp.PIVAAZIENDA, 
	mp.CODICEMATERIAPRIMA,
	CASE 
		WHEN imp.QUANTITADAACQUISTARE >= amp.QUANTITAMINIMADAACQUISTARE THEN
			CEIL((imp.QUANTITADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.QUANTITAPRODOTTO 
		ELSE 
			CEIL((amp.QUANTITAMINIMADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.QUANTITAPRODOTTO
	END AS QUANTITA_DA_ACQUISTARE,
	CASE 
		WHEN imp.QUANTITADAACQUISTARE >= amp.QUANTITAMINIMADAACQUISTARE THEN
			CEIL((imp.QUANTITADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.PREZZOPRODOTTO
		ELSE 
			CEIL((amp.QUANTITAMINIMADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.PREZZOPRODOTTO
	END AS COSTO_TOTALE
FROM AZIENDA_MATERIAPRIMA amp
JOIN MATERIAPRIMA mp ON mp.CODICEMATERIAPRIMA = amp.CODICEMATERIAPRIMA 
JOIN INVENTARIO_MATERIE_PRIME imp ON imp.CODICEMATERIAPRIMA = mp.CODICEMATERIAPRIMA 
WHERE imp.QUANTITADAACQUISTARE > 0
) mp_aconv
WHERE mp_aconv.COSTO_TOTALE = (
	SELECT 
		MIN(mp_aconv1.COSTO_TOTALE) AS COSTO_TOTALE
	FROM (
	SELECT 
		mp.CODICEMATERIAPRIMA,
		CASE 
			WHEN imp.QUANTITADAACQUISTARE >= amp.QUANTITAMINIMADAACQUISTARE THEN
				CEIL((imp.QUANTITADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.PREZZOPRODOTTO
			ELSE 
				CEIL((amp.QUANTITAMINIMADAACQUISTARE/amp.QUANTITAPRODOTTO)) * amp.PREZZOPRODOTTO
		END AS COSTO_TOTALE
	FROM AZIENDA_MATERIAPRIMA amp
	JOIN MATERIAPRIMA mp ON mp.CODICEMATERIAPRIMA = amp.CODICEMATERIAPRIMA 
	JOIN INVENTARIO_MATERIE_PRIME imp ON imp.CODICEMATERIAPRIMA = mp.CODICEMATERIAPRIMA 
	WHERE imp.QUANTITADAACQUISTARE > 0
	ORDER BY imp.CODICEMATERIAPRIMA 
	) mp_aconv1
	WHERE mp_aconv1.CODICEMATERIAPRIMA = mp_aconv.CODICEMATERIAPRIMA
	GROUP BY mp_aconv.CODICEMATERIAPRIMA
)
ORDER BY mp_aconv.CODICEMATERIAPRIMA;