CREATE OR REPLACE VIEW INVENTARIO_PRODOTTO_FINITO AS
SELECT
	p.CODICEPRODOTTO, 
	p.NOMEPRODOTTO, 
	NVL(MAX(pf_prodotti.QUANTITAPRODOTTA), 0) AS QUANTITAPRODOTTA,
	NVL(SUM(dv.QUANTITA), 0) AS QUANTITAVENDUTA,
	NVL(MAX(pf_prodotti.QUANTITAPRODOTTA), 0) - NVL(SUM(dv.QUANTITA), 0) AS QUANTITARIMANENTE
FROM PRODOTTOFINITO p 
LEFT JOIN (
	SELECT 
		c.CODICEPRODOTTOFINITO, 
		SUM(c.QUANTITADAPRODURRE) AS QUANTITAPRODOTTA
	FROM CALENDARIOPRODUZIONE c
	WHERE c.DATAFINEPRODUZIONE < SYSDATE
	GROUP BY c.CODICEPRODOTTOFINITO
) pf_prodotti ON pf_prodotti.CODICEPRODOTTOFINITO = p.CODICEPRODOTTO 
LEFT JOIN DETTAGLIOVENDITA dv ON dv.CODICEPRODOTTO = p.CODICEPRODOTTO
GROUP BY p.CODICEPRODOTTO, p.NOMEPRODOTTO
ORDER BY p.CODICEPRODOTTO;
