CREATE OR REPLACE VIEW "C##COMET".INVENTARIO_PRODOTTI_FINITI AS
SELECT
	p.CODICEPRODOTTO, 
	p.NOMEPRODOTTO, 
	NVL(MAX(pf_prodotti.QUANTITAPRODOTTA), 0) AS QUANTITAPRODOTTA,
	NVL(SUM(dv.QUANTITA), 0) AS QUANTITAVENDUTA,
	NVL(MAX(pf_prodotti.QUANTITAPRODOTTA), 0) - NVL(SUM(dv.QUANTITA), 0) AS QUANTITARIMANENTE
FROM PRODOTTOFINITO p 
LEFT JOIN (
	SELECT 
		pf.CODICEPRODOTTO, 
		SUM(f.PRODUZIONEPREVISTA) AS QUANTITAPRODOTTA
	FROM CALENDARIOPRODUZIONE c
	JOIN FORMULA f ON f.CODICEFORMULA = c.CODICEFORMULA
	JOIN PRODOTTOFINITO pf ON pf.CODICEPRODOTTO = f.CODICEPRODOTTOFINITO
	WHERE c.DATAFINEPRODUZIONE < SYSDATE
	GROUP BY pf.CODICEPRODOTTO 
) pf_prodotti ON pf_prodotti.CODICEPRODOTTO= p.CODICEPRODOTTO 
LEFT JOIN DETTAGLIOVENDITA dv ON dv.CODICEPRODOTTO = p.CODICEPRODOTTO
GROUP BY p.CODICEPRODOTTO, p.NOMEPRODOTTO
ORDER BY p.CODICEPRODOTTO;
