-- "C##DB_COMET".INVENTARIO_PRODOTTI_FINITI source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##DB_COMET"."INVENTARIO_PRODOTTI_FINITI" ("CODICEPRODOTTOFINITO", "NOMEPRODOTTO", "QUANTITAPRODOTTA", "QUANTITACALENDARIZZATA", "QUANTITAVENDUTA", "QUANTITARIMANENTE") AS 
  SELECT
	p.CODICEPRODOTTOFINITO, 
	p.NOMEPRODOTTO, 
	NVL(MAX(pf_prodotti.QUANTITAPRODOTTA), 0) AS QUANTITAPRODOTTA,
	NVL(MAX(pf_da_produrre.QUANTITAPRODOTTA), 0) AS QUANTITACALENDARIZZATA,
	NVL(SUM(dv.QUANTITA), 0) AS QUANTITAVENDUTA,
	NVL(MAX(pf_prodotti.QUANTITAPRODOTTA), 0) + NVL(MAX(pf_da_produrre.QUANTITAPRODOTTA), 0) - NVL(SUM(dv.QUANTITA), 0) AS QUANTITARIMANENTE
FROM PRODOTTOFINITO p 
LEFT JOIN (
	SELECT 
		pf.CODICEPRODOTTOFINITO, 
		SUM(f.PRODUZIONEPREVISTA) AS QUANTITAPRODOTTA
	FROM CALENDARIOPRODUZIONE c
	JOIN FORMULA f ON f.CODICEFORMULA = c.CODICEFORMULA
	JOIN PRODOTTOFINITO pf ON pf.CODICEPRODOTTOFINITO = f.CODICEPRODOTTOFINITO
	WHERE c.DATAFINEPRODUZIONE < SYSDATE
	GROUP BY pf.CODICEPRODOTTOFINITO 
) pf_prodotti ON pf_prodotti.CODICEPRODOTTOFINITO= p.CODICEPRODOTTOFINITO 
LEFT JOIN (
	SELECT 
		pf.CODICEPRODOTTOFINITO, 
		SUM(f.PRODUZIONEPREVISTA) AS QUANTITAPRODOTTA
	FROM CALENDARIOPRODUZIONE c
	JOIN FORMULA f ON f.CODICEFORMULA = c.CODICEFORMULA
	JOIN PRODOTTOFINITO pf ON pf.CODICEPRODOTTOFINITO = f.CODICEPRODOTTOFINITO
	WHERE c.DATAFINEPRODUZIONE >= SYSDATE
	GROUP BY pf.CODICEPRODOTTOFINITO 
) pf_da_produrre ON pf_da_produrre.CODICEPRODOTTOFINITO= p.CODICEPRODOTTOFINITO
LEFT JOIN DETTAGLIOVENDITA dv ON dv.CODICEPRODOTTOFINITO = p.CODICEPRODOTTOFINITO
LEFT JOIN VENDITA v ON v.NUMEROFATTURA = dv.NUMEROFATTURA 
WHERE v.STATOORDINE != 'ANNULLATO'
GROUP BY p.CODICEPRODOTTOFINITO, p.NOMEPRODOTTO
ORDER BY p.CODICEPRODOTTOFINITO;