CREATE OR REPLACE VIEW "C##DB_COMET".INVENTARIO_MATERIE_PRIME AS
SELECT 
	m.CODICEMATERIAPRIMA, 
	m.NOMEPRODOTTO, 
	NVL(MAX(mp_necessarie.QUANTITADAUTILIZZARE), 0) AS QUANTITADAUTILIZZARE, 
	NVL(SUM(da.QUANTITA), 0) AS QUANTITAACQUISTATA,
	NVL(MAX(mp_necessarie.QUANTITADAUTILIZZARE), 0) - NVL(SUM(da.QUANTITA), 0) AS QUANTITADAACQUISTARE
FROM MATERIAPRIMA m 
LEFT JOIN (
	SELECT 
		fm.CODICEMATERIAPRIMA, 
		SUM(fm.QUANTITADAUTILIZZARE) AS QUANTITADAUTILIZZARE
	FROM CALENDARIOPRODUZIONE c 
	JOIN FORMULA f ON f.CODICEPRODOTTOFINITO = c.CODICEPRODOTTOFINITO 
	JOIN FORMULA_MATERIAPRIMA fm ON fm.CODICEFORMULA = f.CODICEFORMULA 
	GROUP BY fm.CODICEMATERIAPRIMA
) mp_necessarie ON mp_necessarie.CODICEMATERIAPRIMA = m.CODICEMATERIAPRIMA
LEFT JOIN DETTAGLIOACQUISTO da ON da.CODICEMATERIAPRIMA = m.CODICEMATERIAPRIMA
GROUP BY m.CODICEMATERIAPRIMA, m.NOMEPRODOTTO
ORDER BY m.CODICEMATERIAPRIMA