SELECT 
	m.CODICEPRODOTTO, 
	m.NOMEPRODOTTO, 
	NVL(MAX(mp_necessarie.QUANTITADAUTILIZZARE), 0) AS QUANTITADAUTILIZZARE, 
	NVL(SUM(da.QUANTITA), 0) AS QUANTITAACQUISTATA,
	NVL(MAX(mp_necessarie.QUANTITADAUTILIZZARE), 0) - NVL(SUM(da.QUANTITA), 0) AS QUANTITADAACQUISTARE
FROM MATERIAPRIMA m 
LEFT JOIN (
	SELECT 
		fm.CODICEPRODOTTOMATERIAPRIMA, 
		SUM(fm.QUANTITADAUTILIZZARE) AS QUANTITADAUTILIZZARE
	FROM CALENDARIOPRODUZIONE c 
	JOIN FORMULA f ON f.CODICEPRODOTTOFINITO = c.CODICEPRODOTTOFINITO 
	JOIN FORMULA_MATERIAPRIMA fm ON fm.CODICEFORMULA = f.CODICEFORMULA 
	GROUP BY fm.CODICEPRODOTTOMATERIAPRIMA
) mp_necessarie ON mp_necessarie.CODICEPRODOTTOMATERIAPRIMA = m.CODICEPRODOTTO
LEFT JOIN DETTAGLIOACQUISTO da ON da.CODICEPRODOTTO = m.CODICEPRODOTTO
GROUP BY m.CODICEPRODOTTO, m.NOMEPRODOTTO
ORDER BY m.CODICEPRODOTTO