-- "C##COMET".INVENTARIO_PRODOTTI_FINITI source

CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##COMET"."INVENTARIO_PRODOTTI_FINITI" ("CODICEPRODOTTO", "NOMEPRODOTTO", "QUANTITAPRODOTTA", "QUANTITAVENDUTA", "QUANTITARIMANENTE") AS 
SELECT
	p.CODICEPRODOTTO, 
	p.NOMEPRODOTTO, 
	NVL(MAX(pf_prodotti.QUANTITAPRODOTTA), 0) AS QUANTITAPRODOTTA,
	NVL(MAX(pf_da_produrre.QUANTITAPRODOTTA), 0) AS QUANTITACALENDARIZZATA,
	NVL(SUM(dv.QUANTITA), 0) AS QUANTITAVENDUTA,
	NVL(MAX(pf_prodotti.QUANTITAPRODOTTA), 0) + NVL(MAX(pf_da_produrre.QUANTITAPRODOTTA), 0) - NVL(SUM(dv.QUANTITA), 0) AS QUANTITARIMANENTE
FROM PRODOTTOFINITO p 
LEFT JOIN (
	SELECT 
		pf.CODICEPRODOTTO, 
		SUM(f.PRODUZIONEPREVISTA) AS QUANTITAPRODOTTA
	FROM CALENDARIOPRODUZIONE c
	JOIN FORMULA f ON f.CODICEFORMULA = c.CODICEFORMULA
	JOIN PRODOTTOFINITO pf ON pf.CODICEPRODOTTO = f.CODICEPRODOTTOFINITO
	WHERE c.DATAFINEPRODUZIONE < SYSDATE
	GROUP BY pf.CODICEPRODOTTO 
) pf_prodotti ON pf_prodotti.CODICEPRODOTTO= p.CODICEPRODOTTO 
LEFT JOIN (
	SELECT 
		pf.CODICEPRODOTTO, 
		SUM(f.PRODUZIONEPREVISTA) AS QUANTITAPRODOTTA
	FROM CALENDARIOPRODUZIONE c
	JOIN FORMULA f ON f.CODICEFORMULA = c.CODICEFORMULA
	JOIN PRODOTTOFINITO pf ON pf.CODICEPRODOTTO = f.CODICEPRODOTTOFINITO
	WHERE c.DATAFINEPRODUZIONE >= SYSDATE
	GROUP BY pf.CODICEPRODOTTO 
) pf_da_produrre ON pf_da_produrre.CODICEPRODOTTO= p.CODICEPRODOTTO
LEFT JOIN DETTAGLIOVENDITA dv ON dv.CODICEPRODOTTO = p.CODICEPRODOTTO
LEFT JOIN VENDITA v ON v.NUMEROFATTURA = dv.NUMEROFATTURA 
WHERE v.STATOORDINE != 'ANNULLATO'
GROUP BY p.CODICEPRODOTTO, p.NOMEPRODOTTO
ORDER BY p.CODICEPRODOTTO;