SELECT fm.CODICEPRODOTTOMATERIAPRIMA, SUM(fm.QUANTITADAUTILIZZARE) AS QUANTITA_UTILIZZATA, NVL(get_quantita_acquistata(fm.CODICEPRODOTTOMATERIAPRIMA), 0) AS QUANTITA_ACQUISTATA
FROM CALENDARIOPRODUZIONE c 
JOIN FORMULA f ON f.CODICEPRODOTTOFINITO = c.CODICEPRODOTTOFINITO 
JOIN FORMULA_MATERIAPRIMA fm ON fm.CODICEFORMULA = f.CODICEFORMULA
GROUP BY fm.CODICEPRODOTTOMATERIAPRIMA
ORDER BY fm.CODICEPRODOTTOMATERIAPRIMA 